version: "3.9"
services:

  mongo_db:
    container_name: my-mongo2
    image: 'mongo:latest'
    restart: always
    ports:
    - '27017:27017'
    volumes:
     - 'mongo_db:/data/db'

  api: 
    build: ./server
    ports:
    - '4000:4000'
    # volumes:
    # - ./server:/app
    # - ./app/node_modules
    environment:
      PORT: 4000
      MONGODB_URI: 'mongodb://mongo_db:27017'
      DB_Name: my-mongodb #productdb2
      NAME: Alyssa Barrett
    depends_on:
    - mongo_db
   
  
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    # volumes:
    #   - ./client:/app
    #   - ./app/node_modules
    stdin_open: true
    tty: true

volumes:
    mongo_db: 