version: "3.9"
services:

  mongo_db:
    container_name: my-mongo2
    image: 'mongo:latest'
    restart: always
    volumes:
     - 'mongo_db:/data/db'

  api: 
    build: .
    ports:
    - '4000:3000'
    environment:
      PORT: 3000
      MONGODB_URI: 'mongodb://mongo_db:27017'
      DB_Name: my-mongodb
      NAME: Alyssa Barrett
    depends_on:
    - mongo_db

volumes:
    mongo_db: 